name: Build and Push Docker Images try

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: drakosha00
          password: ${{ secrets.CR_PAT }}

      - name: Build the Docker image
        run: docker build -t ghcr.io/drakosha00/web-db-app:latest ./app

      - name: Push the Docker image
        run: docker push ghcr.io/drakosha00/web-db-app:latest

      - name: Build & Push DB Image (optional)
        run: echo "Using standard PostgreSQL image, no build needed."
