name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push Web Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/web-app:latest ./app
        docker push ghcr.io/${{ github.repository_owner }}/web-app:latest

    - name: Build & Push DB Image (optional)
      run: |
        echo "Using standard PostgreSQL image, no build needed."
